SELECT CATEGORY_ID, 
       CATEGORY_NAME, 
       SUM(SALES_AMOUNT) AS TOTAL_SALES
FROM SALES
WHERE SALE_DATE BETWEEN TRUNC(SYSDATE, 'MM') AND LAST_DAY(SYSDATE)
GROUP BY CATEGORY_ID, CATEGORY_NAME
ORDER BY TOTAL_SALES DESC;
