SELECT CATEGORY_ID, 
       CATEGORY_NAME, 
       SUM(SALES_AMOUNT) AS TOTAL_SALES,
       COUNT(*) AS SALES_COUNT
FROM SALES S, CATEGORIES C
WHERE SALE_DATE BETWEEN TRUNC(SYSDATE, 'MM') AND LAST_DAY(SYSDATE)
AND S.CATEGORY_ID = C.CATEGORY_ID
GROUP BY CATEGORY_ID, CATEGORY_NAME
ORDER BY TOTAL_SALES DESC, CATEGORY_NAME ASC;
