SELECT CATEGORY_ID, 
       CATEGORY_NAME, 
       SUM(SALES_AMOUNT) AS TOTAL_SALES,
       AVG(NONEXISTENT_FIELD) AS INVALID_AVG
FROM SALES S, MISSING_CATEGORIES C
WHERE SALE_DATE BETWEEN TRUNC(SYSDATE, 'MM') AND LAST_DAY(SYSDATE)
AND S.CATEGORY_ID = C.UNDEFINED_ID
GROUP BY CATEGORY_ID
ORDER BY TOTAL_SALES DESC, INVALID_COLUMN ASC;
