SELECT EMPLOYEE_ID, EMPLOYEE_NAME, SALARY, DEPARTMENT_ID, INVALID_COLUMN
FROM EMPLOYEES E
WHERE SALARY > (
    SELECT AVG(SALARY)
    FROM MISSING_TABLE M
    WHERE M.DEPARTMENT_ID = E.DEPARTMENT_ID
    AND UNDEFINED_FIELD IS NOT NULL
)
ORDER BY DEPARTMENT_ID, SALARY DESC
HAVING COUNT(*) > 0;
