SELECT EMPLOYEE_ID, EMPLOYEE_NAME, SALARY, DEPARTMENT_ID
FROM EMPLOYEES
WHERE SALARY > (
    SELECT AVG(SALARY)
    FROM EMPLOYEES
    WHERE DEPARTMENT_ID = EMPLOYEES.DEPARTMENT_ID
)
ORDER BY DEPARTMENT_ID, SALARY DESC;
