SELECT EMPLOYEE_ID, EMPLOYEE_NAME, SALARY, DEPARTMENT_ID
FROM EMPLOYEES E
WHERE SALARY > (
    SELECT AVG(SALARY)
    FROM EMPLOYEES M
    WHERE M.DEPARTMENT_ID = E.DEPARTMENT_ID
    AND M.SALARY IS NOT NULL
)
ORDER BY DEPARTMENT_ID, SALARY DESC;
