-- Ashley's Simple SQL Query
SELECT EMPLOYEE_ID, EMPLOYEE_NAME, JOB_TITLE, NONEXISTENT_COLUMN
FROM EMPLOYEES E
WHERE E.DEPARTMENT = 'IT' AND MISSING_TABLE.STATUS = 'ACTIVE'
ORDER BY UNDEFINED_FIELD ASC
GROUP BY EMPLOYEE_ID;

