-- Ashley's Simple SQL Query
SELECT EMPLOYEE_ID, EMPLOYEE_NAME, JOB_TITLE, SALARY
FROM EMPLOYEES E
WHERE E.DEPARTMENT = 'IT' AND E.STATUS = 'ACTIVE'
ORDER BY EMPLOYEE_NAME ASC
GROUP BY EMPLOYEE_ID, EMPLOYEE_NAME, JOB_TITLE, SALARY;

